//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 投票记录
    /// </summary>
    [Serializable]
    [Table("cms_VoteLog")]
    public partial class VoteLogInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public VoteLogInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 投票ID
        /// </summary>
        public System.Int32 VoteID { get; set; } = 0;

        /// <summary>
        /// 投票选项ID（GUID）
        /// </summary>
        public System.String VoteItemID { get; set; } = string.Empty;

        /// <summary>
        /// 投票选项
        /// </summary>
        public System.String VoteItemOption { get; set; } = string.Empty;

        /// <summary>
        /// 用户ID
        /// </summary>
        public System.Int32 UserID { get; set; } = 0;

        /// <summary>
        /// 用户名
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;

        /// <summary>
        /// IP地址
        /// </summary>
        public System.String IpAddress { get; set; } = string.Empty;

        /// <summary>
        /// IP区域
        /// </summary>
        public System.String IpArea { get; set; } = string.Empty;

        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";

        /// <summary>
        /// 投票时间
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

    }
}