//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 投票选项
    /// </summary>
    [Serializable]
    public partial class VoteItemInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public VoteItemInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [NotMapped]
        public System.String ItemID { get; set; } = string.Empty;

        /// <summary>
        /// 选项
        /// </summary>
        [NotMapped]
        public System.String VoteOption { get; set; } = string.Empty;

        /// <summary>
        /// 排序号
        /// </summary>
        [NotMapped]
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 投票数量
        /// </summary>
        [NotMapped]
        public System.Int32 VoteNum { get; set; } = 0;

        /// <summary>
        /// 投票占比
        /// </summary>
        [NotMapped]
        public System.Decimal Proportion { get; set; } = 0;

        #endregion

    }
}