//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:46
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using SinGooCMS.Utility.Extension;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 投票调查信息
    /// </summary>
    [Serializable]
    [Table("cms_Vote")]
    public partial class VoteInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public VoteInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 标题
        /// </summary>
        public System.String Title { get; set; } = string.Empty;

        /// <summary>
        /// 投票调查选项
        /// </summary>
        public System.String Items { get; set; } = string.Empty;

        /// <summary>
        /// 是否多选
        /// </summary>
        public System.Boolean IsMultiChoice { get; set; } = false;

        /// <summary>
        /// 是否匿名，如果是匿名投票，通过IP判断唯一性
        /// </summary>
        public System.Boolean IsAnonymous { get; set; } = false;

        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit { get; set; } = false;

        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";

        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;

        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 创建人
        /// </summary>
        public System.String Creator { get; set; } = string.Empty;

        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        #region 扩展属性

        private List<VoteItemInfo> _VoteItems = null;

        /// <summary>
        /// 投票选项集合
        /// </summary>
        [NotMapped]
        public List<VoteItemInfo> VoteItems
        {
            get
            {
                if (_VoteItems != null)
                    return _VoteItems;
                else
                {
                    _VoteItems = this.Items.IsNullOrEmpty()
                                ? null
                                : this.Items.JsonToObject<List<VoteItemInfo>>();
                }
                return _VoteItems;
            }
            set
            {
                _VoteItems = value;
            }
        }

        /// <summary>
        /// 投票选项ID集合
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public System.String[] ItemKeys
        {
            get
            {
                if (this.VoteItems != null && this.VoteItems.Count > 0)
                {
                    var lst = new List<string>();
                    this.VoteItems.ForEach(item =>
                    {
                        lst.Add(item.ItemID);
                    });
                    return lst.ToArray();
                }

                return null;
            }
        }


        #endregion

    }
}