//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:48
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 后台管理菜单
    /// </summary>
    [Serializable]
    [Table("sys_Catalog")]
    public partial class CatalogInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CatalogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 菜单名称
        /// </summary>
        public System.String CatalogName { get; set; } = string.Empty;
        
        /// <summary>
        /// 菜单代号
        /// </summary>
        public System.String CatalogCode { get; set; } = string.Empty;
        
        /// <summary>
        /// 图标
        /// </summary>
        public System.String ImagePath { get; set; } = string.Empty;
        
        /// <summary>
        /// 是否系统，系统菜单不能删除
        /// </summary>
        public System.Boolean IsSystem { get; set; } = false;
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;
        
        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}