//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:48
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 事件日志信息
    /// </summary>
    [Serializable]
    [Table("sys_EventLog")]
    public partial class EventLogInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public EventLogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 用户类型：枚举 UserType
        /// </summary>
        public System.String UserType { get; set; } = string.Empty;
        
        /// <summary>
        /// 日志操作者
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;
        
        /// <summary>
        /// IP
        /// </summary>
        public System.String IPAddress { get; set; } = string.Empty;
        
        /// <summary>
        /// IP区域
        /// </summary>
        public System.String IPArea { get; set; } = string.Empty;
        
        /// <summary>
        /// 事件内容
        /// </summary>
        public System.String EventInfo { get; set; } = string.Empty;

        /// <summary>
        /// 事件类型：枚举 EventType
        /// </summary>
        public System.Int16 EventType { get; set; } = 0;
        
        /// <summary>
        /// 登录失败次数（记录登录事件中失败的次数，累加）
        /// </summary>
        public System.Int16 LoginFailCount { get; set; } = 0;
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}