//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:49
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// IP策略设置
    /// </summary>
    [Serializable]
    [Table("sys_IPStrategy")]
    public partial class IPStrategyInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public IPStrategyInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// IP
        /// </summary>
        public System.String IPAddress { get; set; } = string.Empty;

        /// <summary>
        /// 策略 枚举：IPStrategyType
        /// </summary>
        public System.String Strategy { get; set; } = string.Empty;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}