//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:49
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 模块
    /// </summary>
    [Serializable]
    [Table("sys_Module")]
    public partial class ModuleInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ModuleInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 菜单ID
        /// </summary>
        public System.Int32 CatalogID { get; set; } = 0;

        /// <summary>
        /// 模块名称
        /// </summary>
        public System.String ModuleName { get; set; } = string.Empty;

        /// <summary>
        /// 模块代码
        /// </summary>
        public System.String ModuleCode { get; set; } = string.Empty;

        /// <summary>
        /// 模块文件路径
        /// </summary>
        public System.String FilePath { get; set; } = string.Empty;

        /// <summary>
        /// 图标
        /// </summary>
        public System.String ImagePath { get; set; } = string.Empty;

        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;

        /// <summary>
        /// 是否系统，系统模块不能删除
        /// </summary>
        public System.Boolean IsSystem { get; set; } = false;

        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        /// <summary>
        /// 模板拥有的操作集合
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public IEnumerable<OperateInfo> Operations { get; set; }
    }
}