//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 操作符
    /// </summary>
    [Serializable]
    [Table("sys_Operate")]
    public partial class OperateInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public OperateInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 模块ID
        /// </summary>
        public System.Int32 ModuleID { get; set; } = 0;
        
        /// <summary>
        /// 操作符
        /// </summary>
        public System.String OperateName { get; set; } = string.Empty;

        /// <summary>
        /// 操作代号
        /// </summary>
        public System.String OperateCode { get; set; } = string.Empty;
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;
        
        /// <summary>
        /// 排序号
        /// </summary>
        [Obsolete("这个字段没有意义，待删除")]
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}