//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 权限配置
    /// </summary>
    [Serializable]
    [Table("sys_Purview")]
    public partial class PurviewInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PurviewInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 角色
        /// </summary>
        public System.Int32 RoleID { get; set; } = 0;
        
        /// <summary>
        /// 模块
        /// </summary>
        public System.Int32 ModuleID { get; set; } = 0;
        
        /// <summary>
        /// 操作符
        /// </summary>
        public System.String OperateCode { get; set; } = string.Empty;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}