//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 实体类
    /// </summary>
    [Serializable]
    [Table("sys_Role")]
    public partial class RoleInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public RoleInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 
        /// </summary>
        public System.String RoleName { get; set; } = string.Empty;

        /// <summary>
        /// 
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsSystem { get; set; } = false;

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsManager { get; set; } = false;

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion       

        /// <summary>
        /// 系统固有角色,不可移除
        /// </summary>
        [NotMapped]
        public bool IsSuperAdmin => this.RoleName == "超级管理员";

    }
}