//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 邮件/短信消息发送记录（包括验证码的发送记录）
    /// </summary>
    [Serializable]
    [Table("sys_SendRecord")]
    public partial class SendRecordInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SendRecordInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 发送方式（Mail/SMS）
        /// </summary>
        public System.String SenderType { get; set; } = "Mail";

        /// <summary>
        /// 消息类型 (Common/ValidateCode)
        /// </summary>
        public System.String MsgType { get; set; } = "Common";

        /// <summary>
        /// 消息内容
        /// </summary>
        public System.String MsgBody { get; set; } = string.Empty;

        /// <summary>
        /// 验证码
        /// </summary>
        public System.String ValidateCode { get; set; } = string.Empty;        

        /// <summary>
        /// 接收方（用户名）
        /// </summary>
        public System.String ReciverName { get; set; } = string.Empty;

        /// <summary>
        /// 接收方媒介（邮箱 或者 手机号）
        /// </summary>
        public System.String ReciverMedia { get; set; } = string.Empty;

        /// <summary>
        /// 状态
        /// </summary>
        public System.Byte Status { get; set; } = 0;

        /// <summary>
        /// 返回消息
        /// </summary>
        public System.String ReturnMsg { get; set; } = string.Empty;

        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

    }
}