//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 短信模板（阿里云、腾讯云短信要求使用模板）
    /// </summary>
    [Serializable]
    [Table("sys_SMSTemplate")]
    public partial class SMSTemplateInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SMSTemplateInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 模板名称
        /// </summary>
        public System.String TemplName { get; set; } = string.Empty;
        
        /// <summary>
        /// 模板标题
        /// </summary>
        public System.String TemplTitle { get; set; } = string.Empty;
        
        /// <summary>
        /// 模板代号，参考阿里云/腾讯云短信模板
        /// </summary>
        public System.String TemplCode { get; set; } = string.Empty;

        /// <summary>
        /// 模版内容
        /// </summary>
        public System.String TemplBody { get; set; } = string.Empty;
        
        /// <summary>
        /// 模板占位符 如验证码：${code}，多个占位符用逗号分隔
        /// </summary>
        public System.String TemplKeys { get; set; } = string.Empty;
        
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}