//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 软件版本信息
    /// </summary>
    [Serializable]
    [Table("sys_Ver")]
    public partial class VerInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public VerInfo() 
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public int AutoID { get; set; }

        /// <summary>
        /// 软件名称
        /// </summary>        
        public System.String SoftName { get; set; } = string.Empty;
        
        /// <summary>
        /// 授权开始时间
        /// </summary>
        public System.String LicTimeStart { get; set; } = string.Empty;
        
        /// <summary>
        /// 授权截止时间
        /// </summary>
        public System.String LicTimeEnd { get; set; } = string.Empty;
        
        /// <summary>
        /// 软件版本
        /// </summary>
        public System.String Ver { get; set; } = string.Empty;
        
        /// <summary>
        /// 软件版本号
        /// </summary>
        public System.Int32 VerCodeNum { get; set; } = 0;
        
        /// <summary>
        /// 作者
        /// </summary>
        public System.String Author { get; set; } = string.Empty;
        
        /// <summary>
        /// 公司
        /// </summary>
        public System.String Company { get; set; } = string.Empty;
        
        /// <summary>
        /// 地址
        /// </summary>
        public System.String Address { get; set; } = string.Empty;
        
        /// <summary>
        /// 邮编
        /// </summary>
        public System.String PostCode { get; set; } = string.Empty;       
        
        /// <summary>
        /// 手机号
        /// </summary>
        public System.String Mobile { get; set; } = string.Empty;
        
        /// <summary>
        /// 邮箱
        /// </summary>
        public System.String Email { get; set; } = string.Empty;
                
        /// <summary>
        /// 备注
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;
        
        /// <summary>
        /// 软件最后更新时间
        /// </summary>
        public System.DateTime? LastUpdateTime { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}