//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:56
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;
using SinGooCMS.Utility;

namespace SinGooCMS.Infrastructure
{
    public class IPStrategyRepository : RespositoryBase<IPStrategyInfo>, IIPStrategyRepository
    {
        public IPStrategyRepository()
        {
            //
        }

        public bool IsDeny(string ip, IEnumerable<IPStrategyInfo> lstIPStrategy)
        {
            /*
             * IP有两种形式:1)一个IP地址 如 127.0.0.1  2)一个IP段 如192.168.168.1-192.168.168.255
             * IP策略有两种:1)允许 2)拒绝
             * ip有拒绝策略就认为是拒绝的
             * 有需要再改进，策略应该有优先级，这样有重复设置的时候才能判断是哪个策略起作用
             */

            Func<string, string, bool> IsInIPDuan = (ipCheck, ipSource) =>
            {
                if (ipSource.IndexOf('-') == -1)
                    return ipCheck == ipSource; //固定IP
                else
                {
                    //一个IP段
                    string strBeginIP = ipSource.Split('-')[0];
                    string strEndIP = ipSource.Split('-')[1];
                    return IPUtils.IsInIPDuan(ipCheck, strBeginIP, strEndIP);
                }
            };

            if (lstIPStrategy != null && lstIPStrategy.Count() > 0)
            {
                return lstIPStrategy.Where(p => 
                    EnumUtils.StringToEnum<IPStrategyType>(p.Strategy) == IPStrategyType.DENY 
                    && IsInIPDuan(ip, p.IPAddress))
                    .Any();
            }

            return false;
        }
    }
}