//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:58
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class SendRecordRepository : RespositoryBase<SendRecordInfo>, ISendRecordRepository
    {
        public SendRecordRepository()
        {
            //
        }

        public async Task<SendRecordInfo> GetLatest(string reciverMedia) =>
            await NoTrackQuery()
            .Where(p => p.ReciverMedia == reciverMedia)
            .OrderByDescending(p => p.AutoID)
            .FirstOrDefaultAsync();

        public async Task<SendRecordInfo> GetLatestCheckCode(string reciverMedia) =>
           await NoTrackQuery()
            .Where(p => p.ReciverMedia == reciverMedia && p.ValidateCode != "")
            .OrderByDescending(p => p.AutoID)
            .FirstOrDefaultAsync();
    }
}