//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:59
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;
using SinGooCMS.Utility;

namespace SinGooCMS.Infrastructure
{
    public class VerRepository : RespositoryBase<VerInfo>, IVerRepository
    {
        public VerRepository()
        {
            //
        }
    }
}