//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:46
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class AdPlaceRepository : RespositoryBase<AdPlaceInfo>, IAdPlaceRepository
    {
        public AdPlaceRepository()
        {
            //
        }

        public async Task<bool> DelAdPlace(AdPlaceInfo entity)
        {
            await DbAccess.ExecTransAsync(new List<string>()
            {
                $"delete from cms_AdPlace where AutoID={entity.AutoID};",
                $"delete from cms_Ads where PlaceID={entity.AutoID};"
            });

            return true;
        }

        public async Task<AdPlaceInfo> FindWithItemsAsync(int id)
        {
            var adPlace = await FindAsync(id);
            if (adPlace != null)
                adPlace.ADItems = await dbo.Ads.AsNoTracking().Where(p => p.PlaceID.Equals(id)).ToListAsync();

            return adPlace;
        }
    }
}