//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class AdsRepository : RespositoryBase<AdsInfo>, IAdsRepository
    {
        public AdsRepository()
        {
            //
        }

        public async Task<IEnumerable<AdsInfo>> GetByPlaceID(int placeId) =>
            await NoTrackQuery()
            .Where(p =>
                p.PlaceID.Equals(placeId)
                && (p.BeginDate <= System.DateTime.Now && p.EndDate >= System.DateTime.Now)
                && p.IsAudit)
            .OrderBy(p => p.Sort)
            .ToListAsync();
    }
}