//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class LinksRepository : RespositoryBase<LinksInfo>, ILinksRepository
    {
        public LinksRepository()
        {
            //
        }

        public async Task<IEnumerable<LinksInfo>> GetLinks() =>
           await NoTrackQuery().OrderBy(p => p.Sort).ThenByDescending(p => p.AutoID).ToListAsync();
    }
}