//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IAttachmentRepository : IRepositoryBase<AttachmentInfo>
    {
        /// <summary>
        /// 添加附件
        /// </summary>
        /// <param name="arrFilePath"></param>
        /// <param name="arrRemarks"></param>
        /// <returns></returns>
        Task<string> AddRange(List<string> arrFilePath, List<string> arrRemarks);

        /// <summary>
        /// 获取附件集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        Task<IEnumerable<AttachmentInfo>> GetMutilAsync(string ids);
    }
}