//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface ICommentActiveLogRepository : IRepositoryBase<CommentActiveLogInfo>
    {
        /// <summary>
        /// 点赞
        /// </summary>
        /// <param name="user"></param>
        /// <param name="comment"></param>
        Task<bool> Ding(UserInfo user, CommentInfo comment);
        /// <summary>
        /// 踩
        /// </summary>
        /// <param name="user"></param>
        /// <param name="comment"></param>
        Task<bool> Cai(UserInfo user, CommentInfo comment);
        /// <summary>
        /// 是否用户点赞过
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="commentId"></param>
        /// <returns></returns>
        Task<CommentActiveLogInfo> HasHit(int userId, int commentId);
    }
}