//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:39
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IContFieldRepository : IRepositoryBase<ContFieldInfo>
    {
        /// <summary>
        /// 增加字段
        /// </summary>
        /// <param name="field"></param>
        /// <returns></returns>
        Task<Result> AddField(ContModelInfo model, ContFieldInfo field);
        /// <summary>
        /// 更新字段
        /// </summary>
        /// <param name="field"></param>
        /// <returns></returns>
        Task<Result> UpdateField(ContModelInfo model, ContFieldInfo field);
        /// <summary>
        /// 删除字段
        /// </summary>
        /// <param name="fieldID"></param>
        /// <returns></returns>
        Task<Result> DeleteField(ContFieldInfo field);
        /// <summary>
        /// 删除模型下所有字段
        /// </summary>
        /// <param name="modelID"></param>
        /// <returns></returns>
        Task<bool> DeleteByModelID(int modelID);

        /// <summary>
        /// 读取字段信息
        /// </summary>
        /// <param name="modelID"></param>
        /// <param name="FieldName"></param>
        /// <returns></returns>
        Task<ContFieldInfo> GetField(int modelID, string FieldName);
        /// <summary>
        /// 读取字段列表
        /// </summary>
        /// <param name="modelID"></param>
        /// <param name="isUsing"></param>
        /// <param name="isSystem"></param>
        /// <returns></returns>
        Task<IEnumerable<ContFieldInfo>> GetFields(int modelID, bool? isUsing = null, bool? isSystem = null);
        /// <summary>
        /// 读取非系统字段
        /// </summary>
        /// <param name="modelID"></param>
        /// <returns></returns>
        Task<IEnumerable<ContFieldInfo>> GetNonSystemFields(int modelID);
        /// <summary>
        /// 获取模型下所有字段和值
        /// </summary>
        /// <param name="modelID"></param>
        /// <param name="contID"></param>
        /// <returns></returns>
        Task<IEnumerable<ContFieldInfo>> GetFieldsWithValue(int modelID, int contID);

        /// <summary>
        /// 设置字段是否可用
        /// </summary>
        /// <param name="fieldIds"></param>
        /// <param name="isUsing"></param>
        /// <returns></returns>
        Task<bool> SetEnabled(string fieldIds, bool isUsing = true);
    }
}