//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IFileUploadRepository : IRepositoryBase<FileUploadInfo>
    {
        /// <summary>
        /// 快速添加文件信息
        /// </summary>
        /// <param name="virtualPath"></param>
        /// <param name="userType"></param>
        /// <returns></returns>
        Task<int> Add(string virtualPath, UserType userType = UserType.Manager);

        /// <summary>
        /// 获取文件信息
        /// </summary>
        /// <param name="virtualPath"></param>
        /// <returns></returns>
        Task<FileUploadInfo> GetByFileName(string virtualPath);

        /// <summary>
        /// 获取会员已经上传的文件数量
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
        Task<int> GetUserUpCount(string userName);

        /// <summary>
        /// 获取会员已经上传文件总容量
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
        Task<decimal> GetUserUpTotalSize(string userName);

        /// <summary>
        /// 获取管理员已经上传的文件数量
        /// </summary>
        /// <param name="managerName"></param>
        /// <returns></returns>
        Task<int> GetManagerUpCount(string managerName);
        /// <summary>
        /// 获取管理员已经上传的文件总容量
        /// </summary>
        /// <param name="managerName"></param>
        /// <returns></returns>
        Task<decimal> GetManagerUpTotalSize(string managerName);

        /// <summary>
        /// 批量删除记录,同时删除文件
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        Task<bool> DelBatAndFile(string ids);

        /// <summary>
        ///  移动到文件夹(-1表示未归档)
        /// </summary>
        /// <param name="ids"></param>
        /// <param name="folderID"></param>
        /// <returns></returns>
        Task<bool> MoveToFolder(string ids, int folderID = -1);

        /// <summary>
        /// 未归档文件数量
        /// </summary>
        int UnFiledCount { get; }
    }
}