//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IAutoRlyRepository : IRepositoryBase<AutoRlyInfo>
    {
        /// <summary>
        /// 获取关注回复(微信公众号被关注时自动回复的，只有一条记录)
        /// </summary>
        /// <returns></returns>
        Task<AutoRlyInfo> GetFocusRly();
        /// <summary>
        /// 获取默认回复(没有相对应的关键词时，统一的回复信息，只有一条记录)
        /// </summary>
        /// <returns></returns>
        Task<AutoRlyInfo> GetDefaultRly();
        /// <summary>
        /// 获取关键字回复
        /// </summary>
        /// <param name="strReqKey"></param>
        /// <returns></returns>
        Task<AutoRlyInfo> GetKeyRly(string strReqKey);
        /// <summary>
        /// 获取事件回复
        /// </summary>
        /// <param name="strReqKey"></param>
        /// <returns></returns>
        Task<AutoRlyInfo> GetEventRly(string strReqKey);
        /// <summary>
        /// 获取关键字回复
        /// </summary>
        /// <param name="keyType"></param>
        /// <param name="strMsgKey"></param>
        /// <returns></returns>
        Task<AutoRlyInfo> GetByKey(string keyType, string strMsgKey);
        /// <summary>
        /// 删除事件关键字
        /// </summary>
        /// <param name="strReqKey"></param>
        /// <returns></returns>
        Task<bool> DelEventKey(string strReqKey);
    }
}