//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IWxMenuRepository : IRepositoryBase<WxMenuInfo>
    {
        /// <summary>
        /// 清空本地数据
        /// </summary>
        Task EmptyLocal();
        /// <summary>
        /// 增加菜单
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="eventKey"></param>
        /// <returns></returns>
        Task<WxMenuStatus> Add(WxMenuInfo entity, AutoRlyInfo eventKey);
        /// <summary>
        /// 更新菜单
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="eventKey"></param>
        /// <returns></returns>
        Task<WxMenuStatus> Update(WxMenuInfo entity, AutoRlyInfo eventKey);
        /// <summary>
        /// 删除菜单
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Task<bool> Del(int id);
    }
}