//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class ThirdPartyLoginRepository : RespositoryBase<ThirdPartyLoginInfo>, IThirdPartyLoginRepository
    {
        public ThirdPartyLoginRepository()
        {
            //
        }

        public async Task<bool> ExistsBindUser(string uniqueID) =>
           await NoTrackQuery().Where(p => p.UniqueCert == uniqueID).AnyAsync();

        public async Task<ThirdPartyLoginInfo> GetByUniqueID(string uniqueID) =>
           await NoTrackQuery().Where(p => p.UniqueCert == uniqueID).FirstOrDefaultAsync();

        public async Task<IEnumerable<ThirdPartyLoginInfo>> GetByUser(int userID) =>
           await NoTrackQuery().Where(p => p.BindUserID == userID).ToListAsync();

        public async Task<IEnumerable<ThirdPartyLoginInfo>> GetByUser(string userName) =>
           await NoTrackQuery().Where(p => p.BindUserName == userName).ToListAsync();
    }
}