//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:52
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class UserLevelRepository : RespositoryBase<UserLevelInfo>, IUserLevelRepository
    {
        public UserLevelRepository()
        {
            //
        }

        public async Task<UserLevelInfo> GetInitLevel() =>
            await NoTrackQuery().OrderBy(p => p.Integral).FirstOrDefaultAsync();
    }
}