//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:40
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IAccountRepository : IRepositoryBase<AccountInfo>
    {
        /// <summary>
        /// 增加账户
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> AddAccount(AccountInfo entity);
        /// <summary>
        /// 增加账户
        /// </summary>
        /// <param name="accountName">账户名</param>
        /// <param name="password">密码</param>
        /// <param name="roles">角色</param>
        /// <param name="email"></param>
        /// <param name="phone"></param>
        /// <returns></returns>
        Task<Result> AddAccount(string accountName, string password, string roles = "", string email = "", string phone = "");
        /// <summary>
        /// 更新账户
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> UpdateAccount(AccountInfo entity);
        /// <summary>
        /// 删除账户
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> DelAccount(AccountInfo entity);

        /// <summary>
        /// 管理员登录
        /// </summary>
        /// <param name="accountName"></param>
        /// <param name="password"></param>
        /// <returns></returns>
        Task<AccountInfo> Login(string accountName, string password);

        /// <summary>
        /// 退出登录
        /// </summary>
        /// <param name="account"></param>
        /// <returns></returns>
        void Logout(AccountInfo account);

        /// <summary>
        /// 读取默认管理员账户
        /// </summary>
        /// <returns></returns>
        Task<AccountInfo> GetAdmin();

        /// <summary>
        /// 读取超管账户
        /// </summary>
        /// <returns></returns>
        Task<AccountInfo> GetSuperAdmin();

        /// <summary>
        /// 读取可展示(有权访问)的菜单
        /// </summary>
        /// <returns></returns>
        Task<DataTable> GetMenu(AccountInfo account);
    }
}