//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface ICatalogRepository : IRepositoryBase<CatalogInfo>
    {
        #region 增/改/删除

        /// <summary>
        /// 增加菜单
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> AddMenu(CatalogInfo entity);
        /// <summary>
        /// 修改菜单
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> UpdateMenu(CatalogInfo entity);
        /// <summary>
        /// 删除菜单
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> DelMenu(CatalogInfo entity);

        #endregion

        /// <summary>
        /// 获取菜单信息
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        Task<CatalogInfo> GetByCode(string code);
        /// <summary>
        /// 是否存在菜单代号
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        Task<bool> ExistsCode(string code);
        /// <summary>
        /// 是否存在下级模块
        /// </summary>
        /// <param name="catalogID"></param>
        /// <returns></returns>
        Task<bool> ExistsChildModule(int catalogID);
    }
}