//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IEventLogRepository : IRepositoryBase<EventLogInfo>
    {
        /// <summary>
        /// 最近的1个登录事件
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="userType"></param>
        /// <returns></returns>
        Task<EventLogInfo> GetLatestLoginLog(string userName, UserType userType = UserType.Manager);

        /// <summary>
        /// 最近的1个事件
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="userType"></param>
        /// <returns></returns>
        Task<EventLogInfo> GetLatestEventLog(string userName, UserType userType = UserType.Manager);

        /// <summary>
        /// 重置登录失败次数（重置密码后）
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="userType"></param>
        Task ClearLoginFail(string userName, UserType userType = UserType.User);
    }
}