//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IIPStrategyRepository: IRepositoryBase<IPStrategyInfo>
    {
        /// <summary>
        /// 判断IP是否被拒绝
        /// </summary>
        /// <param name="ip">指定IP</param>
        /// <param name="lstIPStrategy">IP策略集合</param>
        /// <returns></returns>
        bool IsDeny(string ip, IEnumerable<IPStrategyInfo> lstIPStrategy);
    }
}