//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IMessageRepository : IRepositoryBase<MessageInfo>
    {
        /// <summary>
        /// 发送站内信
        /// </summary>
        /// <param name="receivers"></param>
        /// <param name="msg"></param>
        /// <returns></returns>
        Task<bool> SendMsg(IEnumerable<string> receivers, string msg);
        /// <summary>
        /// 阅读站内信
        /// </summary>
        /// <param name="ids"></param>
        Task<bool> ReadMsg(string ids);
        /// <summary>
        /// 设置所有消息已读
        /// </summary>
        /// <param name="receiver"></param>
        /// <returns></returns>
        Task<bool> ReadAll(string receiver);
        /// <summary>
        /// 获取会员未读的站内信总数
        /// </summary>
        /// <param name="receiver"></param>
        /// <returns></returns>
        Task<int> GetNewMsgCount(string receiver);

    }
}