//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IModuleRepository : IRepositoryBase<ModuleInfo>
    {
        /// <summary>
        /// 增加模块
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> AddModule(ModuleInfo entity);
        /// <summary>
        /// 修改模块
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> UpdateModule(ModuleInfo entity);
        /// <summary>
        /// 删除模块
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> DelModule(ModuleInfo entity);

        /// <summary>
        /// 读取模块信息并返回操作种类
        /// </summary>
        /// <param name="moduleId"></param>
        /// <returns></returns>
        Task<ModuleInfo> GetModule(int moduleId);
        /// <summary>
        /// 读取模块信息并返回操作种类
        /// </summary>
        /// <param name="moduleCode"></param>
        /// <returns></returns>
        Task<ModuleInfo> GetModule(string moduleCode);

        /// <summary>
        /// 是否存在模块代号
        /// </summary>
        /// <param name="moduleCode"></param>
        /// <returns></returns>
        Task<bool> ExistsCode(string moduleCode, int currModuleID = 0);

        /// <summary>
        /// 获取菜单下的所有模块
        /// </summary>
        /// <param name="catalogID"></param>
        /// <returns></returns>
        Task<IEnumerable<ModuleInfo>> GetModules(int catalogID);
    }
}