//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IOperateRepository : IRepositoryBase<OperateInfo>
    {
        /// <summary>
        /// 添加操作符
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> AddOperation(OperateInfo entity);
        /// <summary>
        /// 更新操作符
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> UpdateOperation(OperateInfo entity);
        /// <summary>
        /// 删除操作符
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<bool> DelOperation(OperateInfo entity);
        /// <summary>
        /// 是否存在操作符
        /// </summary>
        /// <param name="moduleId">模块ID</param>
        /// <param name="OperationCode">操作符</param>
        /// <param name="currOperationID">更新状态下当前的操作符ID</param>
        /// <returns></returns>
        Task<bool> ExistsCode(int moduleId, string OperationCode, int currOperationID = 0);

        /// <summary>
        /// 添加默认操作
        /// </summary>
        /// <param name="moduleID"></param>
        /// <returns></returns>
        Task<Result> AddDefaultOperate(int moduleID);

        /// <summary>
        /// 获取操作相关集合
        /// </summary>
        /// <returns></returns>
        DataTable GetOperateRelation();
    }
}