//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IPurviewRepository : IRepositoryBase<PurviewInfo>
    {
        /// <summary>
        /// 清除角色的权限设置
        /// </summary>
        /// <param name="roleId"></param>
        Task<bool> DelPurviews(int roleId);

        /// <summary>
        /// 获取角色的权限列表
        /// </summary>
        /// <param name="roleId"></param>
        /// <returns></returns>
        Task<IEnumerable<PurviewInfo>> GetPurviews(int roleId);
        /// <summary>
        /// 保存角色权限
        /// </summary>
        /// <param name="role"></param>
        /// <param name="purviews"></param>
        /// <returns></returns>
        Task<bool> SavePurviews(int roleId, string purviews);
        /// <summary>
        /// 获取账户的权限
        /// </summary>
        /// <param name="account"></param>
        /// <param name="moduleID"></param>
        /// <returns></returns>
        Task<IEnumerable<PurviewInfo>> GetPurviews(AccountInfo account, int moduleID);

    }
}