//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IRoleRepository : IRepositoryBase<RoleInfo>
    {
        /// <summary>
        /// 添加角色
        /// </summary>
        /// <param name="roleName">角色名称，如：内容管理员</param>
        /// <param name="description">描述</param>
        /// <returns></returns>
        Task<int> AddRole(string roleName, string description = "");
        /// <summary>
        /// 设置角色的操作权限
        /// </summary>
        /// <param name="roleId">角色ID</param>
        /// <param name="moduleId">模块ID</param>
        /// <param name="operations">操作种类</param>
        /// <returns></returns>
        Task SetPermissions(int roleId, int moduleId, string operations = "");

        /// <summary>
        /// 读取角色信息
        /// </summary>
        /// <param name="roleName"></param>
        /// <returns></returns>
        Task<RoleInfo> GetByName(string roleName);
        /// <summary>
        /// 删除角色
        /// </summary>
        /// <param name="roleId"></param>
        /// <returns></returns>
        Task<Result> DelRole(int roleId);
        /// <summary>
        /// 是否角色重名
        /// </summary>
        /// <param name="roleName"></param>
        /// <returns></returns>
        Task<bool> ExistsName(string roleName);

        /// <summary>
        /// 读取超管角色信息
        /// </summary>
        /// <returns></returns>
        Task<RoleInfo> GetSuperAdminRole();
    }
}