//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IDictItemRepository : IRepositoryBase<DictItemInfo>
    {
        #region 增/改/删

        /// <summary>
        /// 异步增加字典项
        /// </summary>
        /// <param name="dictInfo"></param>
        /// <returns></returns>
        Task<Result> AddDictItemAsync(DictItemInfo dictInfo);
        /// <summary>
        /// 异步更新字典项
        /// </summary>
        /// <param name="dictInfo"></param>
        /// <returns></returns>
        Task<Result> UpdateDictItemAsync(DictItemInfo dictInfo);
        /// <summary>
        /// 异步删除字典项
        /// </summary>
        /// <param name="dictInfo"></param>
        /// <returns></returns>
        Task<bool> DeleteDictItemAsync(DictItemInfo dictInfo);

        #endregion

        /// <summary>
        /// 是否存在字典键
        /// </summary>
        /// <param name="key"></param>
        /// <param name="Id"></param>
        /// <returns></returns>
        Task<bool> ExistsKey(string key, int Id = 0);

        /// <summary>
        /// 通过字典查找缓存字典项
        /// </summary>
        /// <param name="dictId"></param>
        /// <returns></returns>
        IEnumerable<DictItemInfo> GetCacheItems(int dictId);
        /// <summary>
        /// 通过字典查找缓存字典项
        /// </summary>
        /// <param name="dictName"></param>
        /// <returns></returns>
        IEnumerable<DictItemInfo> GetCacheItems(string dictName);

        /// <summary>
        /// 查找缓存字典项
        /// </summary>
        /// <param name="itemId"></param>
        /// <returns></returns>
        DictItemInfo GetCacheItem(int itemId);

        /// <summary>
        /// 查找缓存字典项
        /// </summary>
        /// <param name="itemKey"></param>
        /// <returns></returns>
        DictItemInfo GetCacheItem(string itemKey);
    }
}