//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface ISettingCategoryRepository : IRepositoryBase<SettingCategoryInfo>
    {
        /// <summary>
        /// 增加自定义设置分类
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> AddSettingCate(SettingCategoryInfo entity);
        /// <summary>
        /// 更新自定义设置分类
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> UpdateSettingCate(SettingCategoryInfo entity);
        /// <summary>
        /// 删除自定义设置分类
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<Result> DelSettingCate(SettingCategoryInfo entity);

        /// <summary>
        /// 是否存在配置项
        /// </summary>
        /// <param name="cateID"></param>
        /// <returns></returns>
        Task<bool> ExistsSetting(int cateID);

        /// <summary>
        /// 是否已存在分类名称
        /// </summary>
        /// <param name="cateName"></param>
        /// <returns></returns>
        Task<bool> ExistsCateName(string cateName, int Id = 0);
    }
}