//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:48
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 基础配置
    /// </summary>
    [Serializable]
    [Table("sys_BaseConfig")]
    public partial class BaseConfigInfo
    {
        public BaseConfigInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public int AutoID { get; set; }

        /// <summary>
        /// 站点名称
        /// </summary>
        public System.String SiteName { get; set; } = string.Empty;

        /// <summary>
        /// 站点图标
        /// </summary>
        public System.String SiteLogo { get; set; } = string.Empty;

        /// <summary>
        /// 站点横幅
        /// </summary>
        public System.String SiteBanner { get; set; } = string.Empty;

        /// <summary>
        /// 站点域名
        /// </summary>
        public System.String SiteDomain { get; set; } = string.Empty;

        /// <summary>
        /// 版权信息
        /// </summary>
        public System.String CopyRight { get; set; } = string.Empty;

        /// <summary>
        /// 备案信息
        /// </summary>
        public System.String IcpNo { get; set; } = string.Empty;

        /// <summary>
        /// 默认语种 如 zh-cn en 
        /// </summary>
        public System.String DefaultLang { get; set; } = string.Empty;

        /// <summary>
        /// 是否启用移动端（启用移动端，需要有相应的模板）
        /// </summary>
        public System.Boolean EnabledMobile { get; set; } = false;

        /// <summary>
        /// 浏览模式 如 MVC默认 伪静态 纯静态
        /// </summary>
        public System.String BrowseType { get; set; } = string.Empty;

        /// <summary>
        /// 地址重写扩展名（MVC之后用不到）
        /// </summary>
        public System.String UrlRewriteExt { get; set; } = string.Empty;

        /// <summary>
        /// 全局分页记录数
        /// </summary>
        public System.Int16 GlobalPageSize { get; set; } = 0;

        /// <summary>
        /// 是否创建静态文章
        /// </summary>
        public System.Boolean IsCreateStaticHTML { get; set; } = true;

        /// <summary>
        /// 生成静态页栏目路径
        /// </summary>
        public System.String HtmlNodeFileRule { get; set; } = string.Empty;

        /// <summary>
        /// 生成静态页详情路径
        /// </summary>
        public System.String HtmlFileRule { get; set; } = string.Empty;

        /// <summary>
        /// 生成静态页扩展名
        /// </summary>
        public System.String HtmlFileExt { get; set; } = string.Empty;

        /// <summary>
        /// 用户名类型（普通、邮箱、手机）
        /// </summary>
        public System.String UserNameType { get; set; } = string.Empty;

        /// <summary>
        /// 普通用户名的正则约束
        /// </summary>
        public System.String UserNameRule { get; set; } = string.Empty;

        /// <summary>
        /// 保留用户名（如Admin,游客等）
        /// </summary>
        public System.String SysUserName { get; set; } = string.Empty;

        /// <summary>
        /// 验证类型
        /// </summary>
        public System.String CertType { get; set; } = string.Empty;

        /// <summary>
        /// 注册协议
        /// </summary>
        public System.String RegAgreement { get; set; } = string.Empty;

        /// <summary>
        /// 注册赠送的积分
        /// </summary>
        public System.Int32 RegGiveIntegral { get; set; } = 0;

        /// <summary>
        /// 推广积分
        /// </summary>
        public System.Int32 TgIntegral { get; set; } = 0;

        /// <summary>
        /// 尝试登录次数（5次登录失败就锁定账户5分钟）
        /// </summary>
        public System.Int16 TryLoginTimes { get; set; } = 0;

        /// <summary>
        /// cookie保存时长
        /// </summary>
        public System.String CookieTime { get; set; } = string.Empty;

        /// <summary>
        /// 注册是否需要验证码
        /// </summary>
        public System.Boolean VerifycodeForReg { get; set; } = false;

        /// <summary>
        /// 登录是否需要验证码
        /// </summary>
        public System.Boolean VerifycodeForLogin { get; set; } = false;

        /// <summary>
        /// 找回密码是否需要验证码
        /// </summary>
        public System.Boolean VerifycodeForGetPwd { get; set; } = false;

        /// <summary>
        /// 找回密码类型
        /// </summary>
        public System.String GetPwdType { get; set; } = string.Empty;

        /// <summary>
        /// 用户文件容量
        /// </summary>
        public System.Int64 FileCapacity { get; set; } = 0;

        /// <summary>
        /// 服务邮箱账号
        /// </summary>
        public System.String ServMailAccount { get; set; } = string.Empty;

        /// <summary>
        /// 服务邮箱用户
        /// </summary>
        public System.String ServMailUserName { get; set; } = string.Empty;

        /// <summary>
        /// 服务邮箱密码
        /// </summary>
        public System.String ServMailUserPwd { get; set; } = string.Empty;

        /// <summary>
        /// 服务邮箱SMTP
        /// </summary>
        public System.String ServMailSMTP { get; set; } = string.Empty;

        /// <summary>
        /// 服务邮箱端口
        /// </summary>
        public System.Int32 ServMailPort { get; set; } = 25;

        /// <summary>
        /// 服务邮箱是否启用SSL
        /// </summary>
        public System.Boolean ServMailIsSSL { get; set; } = false;

        /// <summary>
        /// 收邮件的邮箱
        /// </summary>
        public System.String ReciverEMail { get; set; } = string.Empty;

        /// <summary>
        /// 短信类名
        /// </summary>
        public System.String SMSClass { get; set; } = string.Empty;

        /// <summary>
        /// 是否允许文件上传
        /// </summary>
        public System.Boolean EnableFileUpload { get; set; } = false;

        /// <summary>
        /// 允许上传的文件扩展名
        /// </summary>
        public System.String EnableUploadExt { get; set; } = string.Empty;

        /// <summary>
        /// 每个文件上传限制（KB）
        /// </summary>
        public System.Int32 UploadSizeLimit { get; set; } = 0;

        /// <summary>
        /// 用户上传文件总量限制（KB）
        /// </summary>
        public System.Int32 UploadLimit { get; set; } = 0;

        /// <summary>
        /// 上传文件命名规范
        /// </summary>
        public System.String UploadSaveRule { get; set; } = string.Empty;

        /// <summary>
        /// 上传图片宽度限制，大于此将裁切，0表示无限制
        /// </summary>
        public System.Int32 UploadImgWidthLimit { get; set; } = 0;

        /// <summary>
        /// 上传图片高度限制，大于此将裁切，0表示无限制
        /// </summary>
        public System.Int32 UploadImgHeightLimit { get; set; } = 0;

        /// <summary>
        /// 缩略图尺寸
        /// </summary>
        public System.String ThumbSize { get; set; } = string.Empty;

        /// <summary>
        /// 缩略图模式
        /// </summary>
        public System.String ThumbModel { get; set; } = string.Empty;

        /// <summary>
        /// 水印位置
        /// </summary>
        public System.Byte WaterMarkPosition { get; set; } = 0;

        /// <summary>
        /// 水印类型
        /// </summary>
        public System.String WaterMarkType { get; set; } = string.Empty;

        /// <summary>
        /// 水印文本
        /// </summary>
        public System.String WaterMarkText { get; set; } = string.Empty;

        /// <summary>
        /// 文本水印尺寸
        /// </summary>
        public System.Int16 WaterMarkTextSize { get; set; } = 0;

        /// <summary>
        /// 文本水印字体
        /// </summary>
        public System.String WaterMarkTextFont { get; set; } = string.Empty;

        /// <summary>
        /// 文本水印颜色
        /// </summary>
        public System.String WaterMarkTextColor { get; set; } = string.Empty;

        /// <summary>
        /// 水印图片
        /// </summary>
        public System.String WaterMarkImage { get; set; } = string.Empty;

        /// <summary>
        /// 水印透明度
        /// </summary>
        public System.Double WaterMarkAlpha { get; set; } = 0.0d;

        /// <summary>
        /// 是否启用阿里云OSS存储
        /// </summary>
        public System.Boolean EnableAliyunOSS { get; set; } = false;

        /// <summary>
        /// SEO关键字
        /// </summary>
        public System.String SEOKey { get; set; } = string.Empty;

        /// <summary>
        /// SEO描述
        /// </summary>
        public System.String SEODescription { get; set; } = string.Empty;

        /// <summary>
        /// 脏词
        /// </summary>
        public System.String BadWords { get; set; } = string.Empty;

        /// <summary>
        /// 脏词替换文本
        /// </summary>
        public System.String BWReplaceWord { get; set; } = string.Empty;

        /// <summary>
        /// 是否启访问记录
        /// </summary>
        public System.Boolean VisitRec { get; set; } = false;

        /// <summary>
        /// 站点空间大小，默认是1G
        /// </summary>
        public System.Int64 SiteCapacity { get; set; } = 1073741824;

        /// <summary>
        /// 是否允许外部POST
        /// </summary>
        public System.Boolean AllowOutPost { get; set; } = false;

        /// <summary>
        /// 是否压缩HTML
        /// </summary>
        public System.Boolean IsCompressHtml { get; set; } = false;

        /// <summary>
        /// 主题
        /// </summary>
        public System.String Theme { get; set; } = string.Empty;

        /// <summary>
        /// 默认HTML编辑器
        /// </summary>
        public System.String DefaultHtmlEditor { get; set; } = string.Empty;

        /// <summary>
        /// 统计代码
        /// </summary>
        public System.String STATLink { get; set; } = string.Empty;

        #endregion       

        /// <summary>
        /// 站点网址
        /// </summary>
        [NotMapped]
        public string FullSiteDomain
        {
            get
            {
                if (!SiteDomain.ToLower().StartsWith("http://") && !SiteDomain.ToLower().StartsWith("https://"))
                    return "http://" + SiteDomain.TrimEnd('/');

                return SiteDomain;
            }
        }

        #region Settings

        [NotMapped]
        public Dictionary<string, SettingInfo> CustomSetting { get; set; }

        /// <summary>
        /// 获取自定义配置
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        public SettingInfo GetByKey(string key) => (this.CustomSetting != null && this.CustomSetting.ContainsKey(key))
            ? this.CustomSetting[key]
            : null;

        /// <summary>
        /// 获取自定义设置值
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        [NotMapped]
        public string this[string key] => (this.CustomSetting != null && this.CustomSetting.ContainsKey(key))
            ? this.CustomSetting[key].KeyValue
            : string.Empty;

        #endregion
    }
}