//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:48
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 实体类
    /// </summary>
    [Serializable]
    [Table("sys_Dicts")]
    public partial class DictsInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public DictsInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 字典名称
        /// </summary>
        public System.String DictName { get; set; } = string.Empty;
        
        /// <summary>
        /// 字典描述
        /// </summary>
        public System.String DictDesc { get; set; } = string.Empty;
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing { get; set; } = false;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        #region 自定义属性

        /// <summary>
        /// 字典内容列表
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public IEnumerable<DictItemInfo> Items { get; set; }

        /// <summary>
        /// 字典的内容
        /// </summary>
        /// <param name="keyName"></param>
        /// <returns></returns>
        [NotMapped]
        [JsonIgnore]
        public DictItemInfo this[string keyName] => Items.Where(p => p.KeyName == keyName).FirstOrDefault();

        #endregion
    }
}