//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:50
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SinGooCMS.Utility.Extension;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 自定义配置
    /// </summary>
    [Serializable]
    [Table("sys_Setting")]
    public partial class SettingInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SettingInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 分类ID
        /// </summary>
        public System.Int32 CateID { get; set; } = 0;
        
        /// <summary>
        /// key
        /// </summary>
        public System.String KeyName { get; set; } = string.Empty;
        
        /// <summary>
        /// value
        /// </summary>
        public System.String KeyValue { get; set; } = string.Empty;
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String KeyDesc { get; set; } = string.Empty;
        
        /// <summary>
        /// 提示信息
        /// </summary>
        public System.String Tip { get; set; } = string.Empty;
        
        /// <summary>
        /// 控件类型
        /// </summary>
        public System.String ControlType { get; set; } = string.Empty;
        
        /// <summary>
        /// 数据类型
        /// </summary>
        public System.String DataType { get; set; } = string.Empty;
        
        /// <summary>
        /// 数据长度
        /// </summary>
        public System.Int16 DataLength { get; set; } = 0;
        
        /// <summary>
        /// 默认值
        /// </summary>
        public System.String DefaultValue { get; set; } = string.Empty;
        
        /// <summary>
        /// 前端显示设置
        /// </summary>
        public System.String Setting { get; set; } = string.Empty;
        
        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing { get; set; } = false;
        
        /// <summary>
        /// 是否系统
        /// </summary>
        public System.Boolean IsSystem { get; set; } = false;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        #region 自定义属性

        [NotMapped]
        public FieldSetting FieldSetting => !this.Setting.IsNullOrEmpty() ? this.Setting.JsonToObject<FieldSetting>() : null;

        #endregion

    }
}