//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;
using SinGooCMS.Utility.Extension;

namespace SinGooCMS.Infrastructure
{
    public class AttachmentRepository : RespositoryBase<AttachmentInfo>, IAttachmentRepository
    {
        public AttachmentRepository()
        {
            //
        }

        public async Task<string> AddRange(List<string> arrFilePath, List<string> arrRemarks)
        {
            if (arrFilePath.Count() != arrRemarks.Count())
                throw new Exception("两个参数之间长度不匹配");

            var ids = new List<int>();
            for (int i = 0; i < arrFilePath.Count; i++)
            {
                if (arrFilePath[i].IsNullOrEmpty())
                    continue;

                ids.Add(await AddAsync(new AttachmentInfo()
                {
                    FilePath = arrFilePath[i],
                    ImgThumb = string.Empty,
                    Remark = arrRemarks.Count > i ? arrRemarks[i] : string.Empty,
                    Sort = i + 1,
                    AutoTimeStamp = DateTime.Now
                }));
            }

            return ids.Count > 0
                ? string.Join(",", ids)
                : string.Empty;
        }

        public async Task<IEnumerable<AttachmentInfo>> GetMutilAsync(string ids) =>
            await NoTrackQuery().Where(p => ids.ToIntArray(',').Contains(p.AutoID)).ToListAsync();
    }
}