//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:49
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Data;
using System.Text;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;
using SinGooCMS.Ado;
using SinGooCMS.Ado.Interface;
using SinGooCMS.Utility.Extension;
using SinGooCMS.Utility;

namespace SinGooCMS.Infrastructure
{
    public class ContFieldRepository : RespositoryBase<ContFieldInfo>, IContFieldRepository
    {
        private IDbMaintenance dbMaintenance = DbProvider.DbMaintenance;
        public ContFieldRepository()
        {
            //
        }

        #region 增/改/删

        public async Task<Result> AddField(ContModelInfo model, ContFieldInfo field)
        {
            if (await ExistsAsync(p => p.ModelID == field.ModelID && p.FieldName == field.FieldName))
                return OperateResult.Fail("OperationObjectExists", "操作对象已存在！");

            if (!field.EnableNull && await DbAccess.GetCountAsync(model.TableName) > 0)
                return OperateResult.Fail("Field_HasRowNotEnableNull", "已有数据行不能设置非空列！");

            if (await AddAsync(field) > 0)
            {
                try
                {
                    //副表添加自定义列
                    dbMaintenance.AddColumn(model.TableName, new DbColumnInfo()
                    {
                        ColumnName = field.FieldName,
                        DataType = field.DataType,
                        Length = field.DataLength,
                        DefaultValue = field.DefaultValue,
                        IsNullable = field.EnableNull
                    });

                    return Result.success;
                }
                catch (Exception ex)
                {
                    return OperateResult.Fail("创建数据列异常:" + ex.Message);
                }
            }

            return Result.fail;
        }

        public async Task<Result> UpdateField(ContModelInfo model, ContFieldInfo field)
        {
            //sqlite只支持增加列，不支持修改和删除
            if (EnumUtils.StringToEnum<DbType>(ConfigUtils.ProviderName) == DbType.Sqlite)
                return OperateResult.Fail("OperationNotSupported", "操作不支持！");

            if (field.IsSystem)
                return OperateResult.Fail("Field_SysFieldNotAllowModify", "系统字段不能修改！");

            if (await ExistsAsync(p => p.ModelID == field.ModelID && p.FieldName == field.FieldName && p.AutoID != field.AutoID))
                return OperateResult.Fail("OperationObjectExists", "操作对象已存在！");

            var fieldOld = await FindAsync(field.AutoID); //原字段信息
            if (await UpdateAsync(field))
            {
                try
                {
                    if (fieldOld.FieldName != field.FieldName)
                        dbMaintenance.RenameColumn(model.TableName, fieldOld.FieldName, field.FieldName);

                    dbMaintenance.UpdateColumn(model.TableName, new DbColumnInfo()
                    {
                        ColumnName = field.FieldName,
                        DataType = field.DataType,
                        Length = field.DataLength,
                        DefaultValue = field.DefaultValue,
                        IsNullable = field.EnableNull
                    });

                    return Result.success;
                }
                catch (Exception ex)
                {
                    return OperateResult.Fail("更新数据列异常:" + ex.Message);
                }
            }

            return Result.fail;
        }

        public async Task<Result> DeleteField(ContFieldInfo field)
        {
            //sqlite只支持增加列，不支持修改和删除
            if (EnumUtils.StringToEnum<DbType>(ConfigUtils.ProviderName) == DbType.Sqlite)
                return OperateResult.Fail("OperationNotSupported", "操作不支持！");

            if (field.IsSystem)
                return OperateResult.Fail("Field_SysFieldNotAllowDelete", "系统字段不能删除！");

            try
            {
                var model = await dbo.ContModel.FindAsync(field.ModelID);
                if (await DeleteAsync(field))
                {
                    //删除副表列，列是副表的，非系统的
                    dbMaintenance.DropColumn(model.TableName, field.FieldName);
                    return Result.success;
                }
            }
            catch (Exception ex)
            {
                return OperateResult.Fail("删除数据列异常:" + ex.Message);
            }

            return Result.fail;
        }

        public async Task<bool> DeleteByModelID(int modelID)
        {
            var lstFields = await NoTrackQuery().Where(p => p.ModelID == modelID).ToListAsync();
            if (lstFields != null)
            {
                lstFields.ForEach(async item =>
                {
                    await DeleteField(item);
                });

                return true;
            }

            return false;
        }

        #endregion

        #region 读取字段列表

        public async Task<ContFieldInfo> GetField(int modelID, string FieldName) =>
            await NoTrackQuery().Where(p => p.ModelID == modelID && p.FieldName == FieldName).FirstOrDefaultAsync();

        public async Task<IEnumerable<ContFieldInfo>> GetFields(int modelID, bool? isUsing = null, bool? isSystem = null)
        {
            var query = NoTrackQuery().Where(p => p.ModelID == modelID);
            if (isUsing != null)
                query = query.Where(p => p.IsUsing == isUsing);
            if (isSystem != null)
                query = query.Where(p => p.IsSystem == isSystem);

            return await query.OrderBy(p => p.Sort).ToListAsync();
        }

        public async Task<IEnumerable<ContFieldInfo>> GetNonSystemFields(int modelID)
        {
            var fields = (List<ContFieldInfo>)((await GetFields(modelID, true, false)) ?? new List<ContFieldInfo>());
            fields.Add(Utils.DefaultContFieldInfo);
            return fields;
        }

        public async Task<IEnumerable<ContFieldInfo>> GetFieldsWithValue(int modelID, int contID)
        {
            var fields = await GetFields(modelID, true);
            var model = await dbo.ContModel.FindAsync(modelID);
            var fieldTable = Utils.GetContFieldTable(contID, model.TableName, fields);

            if (fieldTable != null && fieldTable.Rows.Count > 0)
            {
                fields.ForEach(item =>
                {
                    item.Value = fieldTable.Columns.Contains(item.FieldName)
                                ? fieldTable.Rows[0][item.FieldName].ToString()
                                : item.DefaultValue;
                });
            }
            return fields;
        }

        #endregion

        public async Task<bool> SetEnabled(string fieldIds, bool isUsing = true)
        {
            return await UpdateAsync($"IsUsing={(isUsing ? 1 : 0)}", $" {key} in ({fieldIds}) ");
        }
    }
}