//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-04-03 15:48:56
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Infrastructure
{
    public class FolderRepository : RespositoryBase<FolderInfo>, IFolderRepository
    {
        public FolderRepository()
        {
            //
        }

        public async Task<bool> DelFolder(FolderInfo entity)
        {
            //删除文件夹
            if (await DeleteAsync(entity))
            {
                //原所属文件目录标记为未归档(-1)
                await DbAccess.ExecSQLAsync($"update sys_FileUpload set FolderID=-1 where FolderID={entity.AutoID}");
                return true;
            }

            return false;
        }

        public async Task<IEnumerable<FolderInfo>> GetFolderListAsync(int topNum = 200) =>
            await DbAccess.GetListAsync<FolderInfo>(topNum, "", "Sort ASC", "AutoID,FolderName,Remark,Sort,(select count(*) from sys_FileUpload where FolderID=sys_Folder.AutoID) as FileCount");

        public async Task<bool> HasFiles(int folder) =>
            await dbo.FileUpload.AsNoTracking().Where(p => p.FolderID == folder).AnyAsync();
    }
}