//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IAdPlaceRepository : IRepositoryBase<AdPlaceInfo>
    {
        /// <summary>
        /// 删除广告位及所属的广告信息
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        Task<bool> DelAdPlace(AdPlaceInfo entity);
        /// <summary>
        /// 读取广告位及所属广告信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Task<AdPlaceInfo> FindWithItemsAsync(int id);
    }
}