//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IAdsRepository : IRepositoryBase<AdsInfo>
    {
        /// <summary>
        /// 读取广告位的所有广告
        /// </summary>
        /// <param name="placeId"></param>
        /// <returns></returns>
        Task<IEnumerable<AdsInfo>> GetByPlaceID(int placeId);
    }
}