//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:39
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IFeedbackRepository : IRepositoryBase<FeedbackInfo>
    {
        /// <summary>
        /// 发送留言，内容/留言人 必填
        /// </summary>
        /// <param name="content">内容-必填</param>
        /// <param name="userName">留言人名称-必填</param>
        /// <param name="topic">回复的主题-选填</param>
        /// <param name="title">标题-选填</param>
        /// <param name="email">留言人邮箱-选填</param>
        /// <param name="phone">留言人电话-选填</param>
        /// <returns></returns>
        Task<bool> Send(string content, string userName, FeedbackInfo topic = null, string title = "", string email = "", string phone = "");

        /// <summary>
        /// 删除主题及回复
        /// </summary>
        /// <param name="rootId"></param>
        /// <returns></returns>
        Task<bool> DelTopicAsync(int rootId);

        /// <summary>
        /// 删除多项
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        Task<bool> DelMutli(string ids);

        /// <summary>
        /// 获得分页数据（包含回复数）
        /// </summary>
        /// <param name="condition"></param>
        /// <param name="sort"></param>
        /// <param name="pageIndex"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        Task<PagerModel<IEnumerable<FeedbackInfo>>> GetPagerWithReplyCount(string condition, string sort, int pageIndex, int pageSize);
    }
}