//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:39
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface ILinksRepository : IRepositoryBase<LinksInfo>
    {
        /// <summary>
        /// 读取友情链接
        /// </summary>
        /// <returns></returns>
        Task<IEnumerable<LinksInfo>> GetLinks();
    }
}