//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 广告位信息
    /// </summary>
    [Serializable]
    [Table("cms_AdPlace")]
    public partial class AdPlaceInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AdPlaceInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 自增主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 广告位名称
        /// </summary>
        public System.String PlaceName { get; set; } = string.Empty;

        /// <summary>
        /// 广告长
        /// </summary>
        public System.Int16 Width { get; set; } = 0;

        /// <summary>
        /// 广告宽
        /// </summary>
        public System.Int16 Height { get; set; } = 0;

        /// <summary>
        /// 价格
        /// </summary>
        public System.Decimal Price { get; set; } = 0.0m;

        /// <summary>
        /// 广告模板
        /// </summary>
        public System.String TemplateFile { get; set; } = string.Empty;

        /// <summary>
        /// 描述
        /// </summary>
        public System.String PlaceDesc { get; set; } = string.Empty;

        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";

        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        /// <summary>
        /// 广告信息
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public IEnumerable<AdsInfo> ADItems { get; set; }

        /// <summary>
        /// 有效的广告信息
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public Lazy<IEnumerable<AdsInfo>> ValidADItems => new Lazy<IEnumerable<AdsInfo>>(() =>
        {
            return ADItems?.Where(p => p.PlaceID.Equals(this.AutoID) && (p.BeginDate <= System.DateTime.Now && p.EndDate >= System.DateTime.Now) && p.IsAudit);
        });

        /// <summary>
        /// 是否包含广告
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public Lazy<bool> HasAds => new Lazy<bool>(() =>
        {
            return ADItems?.Count() > 0;
        });
    }
}