//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 广告信息
    /// </summary>
    [Serializable]
    [Table("cms_Ads")]
    public partial class AdsInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AdsInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 广告位
        /// </summary>
        public System.Int32 PlaceID { get; set; } = 0;
        
        /// <summary>
        /// 广告名称
        /// </summary>
        public System.String AdName { get; set; } = string.Empty;
        
        /// <summary>
        /// 广告类型
        /// </summary>
        public System.Byte AdType { get; set; } = 0;
        
        /// <summary>
        /// 广告链接
        /// </summary>
        public System.String AdLink { get; set; } = string.Empty;
        
        /// <summary>
        /// 开始时间
        /// </summary>
        public System.DateTime? BeginDate { get; set; } = new DateTime(1900, 1, 1);
        
        /// <summary>
        /// 结束时间
        /// </summary>
        public System.DateTime? EndDate { get; set; } = new DateTime(1900, 1, 1);
        
        /// <summary>
        /// 广告文本
        /// </summary>
        public System.String AdText { get; set; } = string.Empty;
        
        /// <summary>
        /// 广告媒体（文字、图片）
        /// </summary>
        public System.String AdMediaPath { get; set; } = string.Empty;
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String AdDesc { get; set; } = string.Empty;
        
        /// <summary>
        /// 是否新窗口打开
        /// </summary>
        public System.Boolean IsNewWin { get; set; } = false;
        
        /// <summary>
        /// 点击数量
        /// </summary>
        public System.Int32 Hit { get; set; } = 0;
        
        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit { get; set; } = false;
        
        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}