//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:44
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 留言信息
    /// </summary>
    [Serializable]
    [Table("cms_Feedback")]
    public partial class FeedbackInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public FeedbackInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 根ID
        /// </summary>
        public System.Int32 RootID { get; set; } = 0;
        
        /// <summary>
        /// 回复的留言ID
        /// </summary>
        public System.Int32 ReplyID { get; set; } = 0;
        
        /// <summary>
        /// 用户ID
        /// </summary>
        public System.Int32 UserID { get; set; } = 0;
        
        /// <summary>
        /// 用户名称
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;
        
        /// <summary>
        /// 标题
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        
        /// <summary>
        /// 内容
        /// </summary>
        public System.String Content { get; set; } = string.Empty;       
        
        /// <summary>
        /// 邮箱
        /// </summary>
        public System.String Email { get; set; } = string.Empty;
        
        /// <summary>
        /// 电话
        /// </summary>
        public System.String Phone { get; set; } = string.Empty;

        /// <summary>
        /// IP地址
        /// </summary>
        public System.String IPAddress { get; set; } = string.Empty;

        /// <summary>
        /// IP地理位置
        /// </summary>
        public System.String IPArea { get; set; } = string.Empty;

        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit { get; set; } = false;
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        /// <summary>
        /// 回复数
        /// </summary>
        [NotMapped]
        public int ReplyCount { get; set; }
        
    }
}