//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:40
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IVoteRepository : IRepositoryBase<VoteInfo>
    {
        /// <summary>
        /// 删除投票信息及投票记录
        /// </summary>
        /// <param name="voteInfo"></param>
        /// <returns></returns>
        Task<bool> DelVote(VoteInfo voteInfo);
        /// <summary>
        /// 删除投票信息及投票记录
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        Task<bool> DelVotes(string ids);
        /// <summary>
        /// 读取投票信息
        /// </summary>
        /// <param name="voteId"></param>
        /// <returns></returns>
        Task<VoteInfo> GetVoteFull(int voteId);
    }
}