//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 账户明细，积分增加影响会员等级的提升
    /// </summary>
    [Serializable]
    [Table("cms_AccountDetail")]
    public partial class AccountDetailInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AccountDetailInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 会员ID
        /// </summary>
        public System.Int32 UserID { get; set; } = 0;
        
        /// <summary>
        /// 会员名
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;
        
        /// <summary>
        /// 单位：Amount or Integral
        /// </summary>
        public System.String Unit { get; set; } = string.Empty;
        
        /// <summary>
        /// 操作前
        /// </summary>
        public System.Double Before { get; set; } = 0.0d;
        
        /// <summary>
        /// 操作值
        /// </summary>
        public System.Double OpValue { get; set; } = 0.0d;
        
        /// <summary>
        /// 类型 增/减
        /// </summary>
        public System.Byte OpType { get; set; } = 0;
        
        /// <summary>
        /// 操作后
        /// </summary>
        public System.Double After { get; set; } = 0.0d;
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;
        
        /// <summary>
        /// 操作者
        /// </summary>
        public System.String Operator { get; set; } = string.Empty;
        
        /// <summary>
        /// 操作时间
        /// </summary>
        public System.DateTime? OperateDate { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}