//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:45
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 第三方登录信息
    /// </summary>
    [Serializable]
    [Table("cms_ThirdPartyLogin")]
    public partial class ThirdPartyLoginInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ThirdPartyLoginInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 登录来源
        /// </summary>
        public System.String LoginFrom { get; set; } = string.Empty;
        
        /// <summary>
        /// 唯一认证值（用于确认第三方用户的唯一值）
        /// </summary>
        public System.String UniqueCert { get; set; } = string.Empty;
        
        /// <summary>
        /// 绑定的用户ID
        /// </summary>
        public System.Int32 BindUserID { get; set; } = 0;
        
        /// <summary>
        /// 绑定的用户名
        /// </summary>
        public System.String BindUserName { get; set; } = string.Empty;
        
        /// <summary>
        /// token
        /// </summary>
        public System.String AccessToken { get; set; } = string.Empty;

        /// <summary>
        /// token
        /// </summary>
        public System.String RefreshToken { get; set; } = string.Empty;
        
        /// <summary>
        /// 登录时间
        /// </summary>
        public System.DateTime? LoginTime { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}