//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:46
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using Newtonsoft.Json;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 会员信息
    /// </summary>
    [Serializable]
    [Table("cms_User")]
    public partial class UserInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public UserInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 会员名称
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;

        /// <summary>
        /// 会员组
        /// </summary>
        public System.Int32 GroupID { get; set; } = 0;

        /// <summary>
        /// 会员等级
        /// </summary>
        public System.Int32 LevelID { get; set; } = 0;

        /// <summary>
        /// 密码
        /// </summary>
        public System.String Password { get; set; } = string.Empty;

        /// <summary>
        /// 绑定的邮箱地址
        /// </summary>
        public System.String Email { get; set; } = string.Empty;

        /// <summary>
        /// 绑定的手机号
        /// </summary>
        public System.String Mobile { get; set; } = string.Empty;

        /// <summary>
        /// 余额
        /// </summary>
        public System.Decimal Amount { get; set; } = 0.0m;

        /// <summary>
        /// 积分
        /// </summary>
        public System.Int32 Integral { get; set; } = 0;

        /// <summary>
        /// 文件存储空间容量
        /// </summary>
        public System.Int32 FileSpace { get; set; } = 0;

        /// <summary>
        /// 证件类型
        /// </summary>
        public System.String CertType { get; set; } = string.Empty;

        /// <summary>
        /// 证件号
        /// </summary>
        public System.String CertNo { get; set; } = string.Empty;

        /// <summary>
        /// 昵称
        /// </summary>
        public System.String NickName { get; set; } = string.Empty;

        /// <summary>
        /// 真实姓名
        /// </summary>
        public System.String RealName { get; set; } = string.Empty;

        /// <summary>
        /// 性别
        /// </summary>
        public System.String Gender { get; set; } = string.Empty;

        /// <summary>
        /// 生日
        /// </summary>
        public System.DateTime? Birthday { get; set; } = new DateTime(1900, 1, 1);

        /// <summary>
        /// 头像
        /// </summary>
        public System.String HeaderPhoto { get; set; } = string.Empty;

        /// <summary>
        /// 信用额度
        /// </summary>
        public System.Decimal CreditLine { get; set; } = 0.0m;

        /// <summary>
        /// 地区
        /// </summary>
        public System.String Area { get; set; } = string.Empty;

        /// <summary>
        /// 国家
        /// </summary>
        public System.String Country { get; set; } = string.Empty;

        /// <summary>
        /// 省份
        /// </summary>
        public System.String Province { get; set; } = string.Empty;

        /// <summary>
        /// 城市
        /// </summary>
        public System.String City { get; set; } = string.Empty;

        /// <summary>
        /// 县区
        /// </summary>
        public System.String County { get; set; } = string.Empty;

        /// <summary>
        /// 详细地址
        /// </summary>
        public System.String Address { get; set; } = string.Empty;

        /// <summary>
        /// 邮编
        /// </summary>
        public System.String PostCode { get; set; } = string.Empty;

        /// <summary>
        /// 座机电话
        /// </summary>
        public System.String TelePhone { get; set; } = string.Empty;

        /// <summary>
        /// 支付密码
        /// </summary>
        public System.String PayPassword { get; set; } = string.Empty;

        /// <summary>
        /// 备注说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;

        /// <summary>
        /// 是否第三方登录
        /// </summary>
        public System.Boolean IsThirdLoginReg { get; set; } = false;

        /// <summary>
        /// 状态：0未审核 99已审核
        /// </summary>
        public System.Byte Status { get; set; } = (int)UserStatus.WaitAudit;

        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 登录次数
        /// </summary>
        public System.Int32 LoginCount { get; set; } = 0;

        /// <summary>
        /// 最后登录时间
        /// </summary>
        public System.DateTime? LastLoginTime { get; set; } = new DateTime(1900, 1, 1);

        /// <summary>
        /// 最后登录IP
        /// </summary>
        public System.String LastLoginIP { get; set; } = string.Empty;

        /// <summary>
        /// 注册时间
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        #region 自定义属性

        /// <summary>
        /// 自定义表
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public DataTable CustomTable { get; set; }

        /// <summary>
        /// 自定义表行
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public DataRow Items => (CustomTable != null && CustomTable.Rows.Count > 0) ? CustomTable.Rows[0] : null;

        /// <summary>
        /// 读取自定义表字段
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public object Get(string name) => Items != null ? Items[name] : string.Empty;

        #endregion

    }
}