//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:46
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SinGooCMS.Utility.Extension;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 副表字段
    /// </summary>
    [Serializable]
    [Table("cms_UserField")]
    public partial class UserFieldInfo : IField
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public UserFieldInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 用户组ID
        /// </summary>
        public System.Int32 UserGroupID { get; set; } = 0;

        /// <summary>
        /// 字段名称
        /// </summary>
        public System.String FieldName { get; set; } = string.Empty;

        /// <summary>
        /// 字段类型 参看：SinGooCMS.FieldType
        /// </summary>
        public System.String FieldType { get; set; } = string.Empty;

        /// <summary>
        /// 数据类型（这里是sqlserver数据类型）
        /// </summary>
        public System.String DataType { get; set; } = string.Empty;

        /// <summary>
        /// 数据长度
        /// </summary>
        public System.Int16 DataLength { get; set; } = 0;

        /// <summary>
        /// 别名
        /// </summary>
        public System.String FieldAlias { get; set; } = string.Empty;

        /// <summary>
        /// 提示消息
        /// </summary>
        public System.String Tip { get; set; } = string.Empty;

        /// <summary>
        /// 描述
        /// </summary>
        public System.String FieldDesc { get; set; } = string.Empty;

        /// <summary>
        /// 默认值
        /// </summary>
        public System.String DefaultValue { get; set; } = string.Empty;

        /// <summary>
        /// 设置
        /// </summary>
        public System.String Setting { get; set; } = string.Empty;

        /// <summary>
        /// 是否允许空值
        /// </summary>
        public System.Boolean EnableNull { get; set; } = false;

        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing { get; set; } = false;

        /// <summary>
        /// 是否系统
        /// </summary>
        public System.Boolean IsSystem { get; set; } = false;

        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        #region 自定义属性

        /// <summary>
        /// 字段的值
        /// </summary>
        [NotMapped]
        public string Value { get; set; } = null;

        /// <summary>
        /// 设置
        /// </summary>
        [NotMapped]
        public FieldSetting Settings => this.Setting.JsonToObject<FieldSetting>();

        #endregion

    }
}