//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:46
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 会员组信息
    /// </summary>
    [Serializable]
    [Table("cms_UserGroup")]
    public partial class UserGroupInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public UserGroupInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 会员组名称
        /// </summary>
        public System.String GroupName { get; set; } = string.Empty;
        
        /// <summary>
        /// 副表
        /// </summary>
        public System.String TableName { get; set; } = string.Empty;
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String GroupDesc { get; set; } = string.Empty;
        
        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 创建者
        /// </summary>
        public System.String Creator { get; set; } = string.Empty;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}