//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using SinGooCMS.Domain.Interface;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 评论表
    /// </summary>
    [Serializable]
    [Table("cms_Comment")]
    public partial class CommentInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CommentInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 被评论的文章内容ID
        /// </summary>
        public System.Int32 ContID { get; set; } = 0;

        /// <summary>
        /// 回复的评论ID
        /// </summary>
        public System.Int32 ReplyID { get; set; } = 0;

        /// <summary>
        /// 发表评论的用户
        /// </summary>
        public System.Int32 UserID { get; set; } = 0;

        /// <summary>
        /// 发表评论的用户名
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;

        /// <summary>
        /// 评论内容
        /// </summary>
        public System.String Comment { get; set; } = string.Empty;

        /// <summary>
        /// IP地址
        /// </summary>
        public System.String IPAddress { get; set; } = string.Empty;

        /// <summary>
        /// IP地域
        /// </summary>
        public System.String IPArea { get; set; } = string.Empty;

        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit { get; set; } = false;

        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";

        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion        

        /// <summary>
        /// 回复的数量
        /// </summary>
        [NotMapped]
        public int ReplyCount { get; set; }

        /// <summary>
        /// 点赞的数量
        /// </summary>
        [NotMapped]
        public System.Int32 ZanCount { get; set; } = 0;

        /// <summary>
        /// 点踩的数量
        /// </summary>
        [NotMapped]
        public System.Int32 CaiCount { get; set; } = 0;
    }
}