//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 评论点赞表
    /// </summary>
    [Serializable]
    [Table("cms_CommentActiveLog")]
    public partial class CommentActiveLogInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CommentActiveLogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 评论ID
        /// </summary>
        public System.Int32 CommentID { get; set; } = 0;

        /// <summary>
        /// 点赞人
        /// </summary>
        public System.Int32 UserID { get; set; } = 0;
        
        /// <summary>
        /// 点赞人用户名
        /// </summary>
        public System.String UserName { get; set; } = string.Empty;
        
        /// <summary>
        /// IP地址
        /// </summary>
        public System.String IPAddress { get; set; } = string.Empty;
        
        /// <summary>
        /// IP地域
        /// </summary>
        public System.String IPArea { get; set; } = string.Empty;
        
        /// <summary>
        /// 是否赞 true=赞 false=踩
        /// </summary>
        public System.Boolean IsZan { get; set; } = false;
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}