//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 文章内容
    /// </summary>
    [Serializable]
    [Table("cms_Content")]
    public partial class ContentBaseInfo
    {
        public ContentBaseInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 栏目ID
        /// </summary>
        public System.Int32 NodeID { get; set; } = 0;

        /// <summary>
        /// 模型ID
        /// </summary>
        public System.Int32 ModelID { get; set; } = 0;

        /// <summary>
        /// 副表表名
        /// </summary>
        public System.String TableName { get; set; } = string.Empty;

        /// <summary>
        /// 标题
        /// </summary>
        public System.String Title { get; set; } = string.Empty;

        /// <summary>
        /// 副标题
        /// </summary>
        public System.String SubTitle { get; set; } = string.Empty;

        /// <summary>
        /// 摘要
        /// </summary>
        public System.String Summary { get; set; } = string.Empty;

        /// <summary>
        /// 内容图片
        /// </summary>
        public System.String ContentImage { get; set; } = string.Empty;

        /// <summary>
        /// 点击量
        /// </summary>
        public System.Int32 Hit { get; set; } = 0;

        /// <summary>
        /// 是否置顶
        /// </summary>
        public System.Boolean IsTop { get; set; } = false;

        /// <summary>
        /// 是否推荐
        /// </summary>
        public System.Boolean IsRecommend { get; set; } = false;

        /// <summary>
        /// 是否最新
        /// </summary>
        public System.Boolean IsNew { get; set; } = false;

        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;

        /// <summary>
        /// 状态
        /// </summary>
        public System.Int16 Status { get; set; } = (int)ContStatus.DraftBox; //初始化默认是草稿箱

        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);

        #endregion

        #region 自定义属性

        /// <summary>
        /// 副表信息
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public DataTable CustomTable { get; set; }

        [NotMapped]
        [JsonIgnore]
        public DataRow Items => (CustomTable != null && CustomTable.Rows.Count > 0) ? CustomTable.Rows[0] : null;

        public object Get(string name) => Items != null ? Items[name] : string.Empty;

        /// <summary>
        /// 评论数量
        /// </summary>
        [NotMapped]
        public int CommentCount { get; set; }

        /// <summary>
        /// 相关内容(字典：int:ID,string:标题)
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public IDictionary<int, string> RelationContentDict { get; set; }

        /// <summary>
        /// 文章地址
        /// </summary>
        [NotMapped]
        public string ContentUrl { get; set; }

        /// <summary>
        /// 基本字段
        /// </summary>
        [NotMapped]
        [JsonIgnore]
        public static string ShortFields =>
            "AutoID,NodeID,ModelID,TableName,Title,SubTitle,Summary,ContentImage,Hit,IsTop,IsRecommend,IsNew,Sort,Status,AutoTimeStamp";

        #endregion        

    }
}