//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:44
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 文章内容与栏目多对多扩展关系
    /// </summary>
    [Serializable]
    [Table("cms_ContNodeExt")]
    public partial class ContNodeExtInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ContNodeExtInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;

        /// <summary>
        /// 栏目ID
        /// </summary>
        public System.Int32 NodeID { get; set; } = 0;

        /// <summary>
        /// 文章内容ID
        /// </summary>
        public System.Int32 ContID { get; set; } = 0;


        #endregion

    }
}