//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:45
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 标签
    /// </summary>
    [Serializable]
    [Table("cms_Tags")]
    public partial class TagsInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public TagsInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 标签名
        /// </summary>
        public System.String TagName { get; set; } = string.Empty;
        
        /// <summary>
        /// 地址
        /// </summary>
        public System.String TagUrl { get; set; } = string.Empty;
        
        /// <summary>
        /// 用于云标签的下标
        /// </summary>
        public System.Int32 TagIndex { get; set; } = 0;
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark { get; set; } = string.Empty;
        
        /// <summary>
        /// 是否置顶
        /// </summary>
        public System.Boolean IsTop { get; set; } = false;
        
        /// <summary>
        /// 是否推荐
        /// </summary>
        public System.Boolean IsRecommend { get; set; } = false;
        
        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang { get; set; } = "zh-cn";
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}