//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IAccountDetailRepository: IRepositoryBase<AccountDetailInfo>
    {
        /// <summary>
        ///  添加账户金额明细
        /// </summary>
        /// <param name="user"></param>
        /// <param name="intOpType"></param>
        /// <param name="douOpValue"></param>
        /// <param name="strRemark"></param>
        /// <returns></returns>
        Task<bool> AddAmount(UserInfo user, int intOpType, double douOpValue, string strRemark);
        /// <summary>
        /// 添加账户积分明细
        /// </summary>
        /// <param name="user"></param>
        /// <param name="intOpType"></param>
        /// <param name="douOpValue"></param>
        /// <param name="strRemark"></param>
        /// <returns></returns>
        Task<bool> AddIntegral(UserInfo user, int intOpType, double douOpValue, string strRemark);
    }
}