//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 11:10:40
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SinGooCMS.Domain.Models;

namespace SinGooCMS.Domain.Interface
{
    public interface IUserGroupRepository: IRepositoryBase<UserGroupInfo>
    {
        /// <summary>
        /// 添加会员组
        /// </summary>
        /// <param name="groupName">会员组名</param>
        /// <param name="viceTableName">副表名</param>
        /// <returns></returns>
        Task<Result> AddGroup(string groupName, string viceTableName);
        /// <summary>
        /// 添加会员组
        /// </summary>
        /// <param name="group"></param>
        /// <returns></returns>
        Task<Result> AddGroup(UserGroupInfo group);
        /// <summary>
        /// 更新会员组
        /// </summary>
        /// <param name="group"></param>
        /// <returns></returns>
        Task<bool> UpdateGroup(UserGroupInfo group);
        /// <summary>
        /// 删除会员组
        /// </summary>
        /// <param name="group"></param>
        /// <returns></returns>
        Task<Result> DelGroup(UserGroupInfo group);

        /// <summary>
        /// 读取会员组
        /// </summary>
        /// <param name="groupId"></param>
        /// <returns></returns>
        Task<UserGroupInfo> GetGroup(int groupId);
        /// <summary>
        /// 读取会员组
        /// </summary>
        /// <param name="groupName"></param>
        /// <returns></returns>
        Task<UserGroupInfo> GetGroup(string groupName);
        /// <summary>
        /// 读取缓存会员组
        /// </summary>
        /// <param name="groupId"></param>
        /// <returns></returns>
        UserGroupInfo GetCacheGroup(int groupId);
        /// <summary>
        /// 读取缓存会员组
        /// </summary>
        /// <param name="groupName"></param>
        /// <returns></returns>
        UserGroupInfo GetCacheGroup(string groupName);

        /// <summary>
        /// 默认的会员组
        /// </summary>
        /// <returns></returns>
        UserGroupInfo GetCacheDefGroup();

    }
}