//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:16826375@qq.com http://www.singoo.top
//     生成时间为:2020-03-31 10:35:51
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinGooCMS.Domain.Models
{
    /// <summary>
    /// 微信菜单，微信公众号底部菜单
    /// </summary>
    [Serializable]
    [Table("weixin_WxMenu")]
    public partial class WxMenuInfo
    {
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public WxMenuInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public System.Int32 AutoID { get; set; } = 0;
        
        /// <summary>
        /// 根ID
        /// </summary>
        public System.Int32 RootID { get; set; } = 0;
        
        /// <summary>
        /// 上级ID
        /// </summary>
        public System.Int32 ParentID { get; set; } = 0;
        
        /// <summary>
        /// 类型：click or view
        /// </summary>
        public System.String Type { get; set; } = string.Empty;
        
        /// <summary>
        /// 菜单名称
        /// </summary>
        public System.String Name { get; set; } = string.Empty;
        
        /// <summary>
        /// 关键字
        /// </summary>
        public System.String EventKey { get; set; } = string.Empty;
        
        /// <summary>
        /// 链接网址
        /// </summary>
        public System.String Url { get; set; } = string.Empty;
        
        /// <summary>
        /// 子菜单数量
        /// </summary>
        public System.Int16 ChildCount { get; set; } = 0;
        
        /// <summary>
        /// 子菜单ID集合
        /// </summary>
        public System.String ChildIDs { get; set; } = string.Empty;
        
        /// <summary>
        /// 排序号
        /// </summary>
        public System.Int32 Sort { get; set; } = 99999;
        
        /// <summary>
        /// 时间戳
        /// </summary>
        public System.DateTime? AutoTimeStamp { get; set; } = new DateTime(1900, 1, 1);
                
        #endregion
        
    }
}